### ISSUE TITLE
initial-value error

### ISSUE THREAD

**Issue by qwe3244968** [seanny1986/gym-aero#11]
I want to use the model of“hover”，when i set the  initial-value of action as [0,0,0,0] , the quadrotor fly up ! Isn't it keep balance？thank you for your answering！

**Comment by seanny1986** [comment]
Yeah, I just moved everything over to a new simulator, and found that bug a few days ago. There was a problem with how the RPM was being applied, which I've since fixed but haven't pushed through yet. I'll push the latest version tonight; I'm still in the process of validating everything, but that should be done in a few hours.

I'll drop a response here once I've updated everything.

**Comment by seanny1986** [comment]
I pushed the latest version through -- took a while since I wanted to verify that the new simulation was working as intended. If you try inputting a hover command now, it should stay static.

**Comment by qwe3244968** [comment]
I will try!Thank you very much!Now,I am trying to complete some tasks in your environment(past version) by Deep Reinforcement learning.I am honored to be helped by you!




------------------ 原始邮件 ------------------
发件人: "Sean Morrison"<notifications@github.com>;
发送时间: 2019年7月15日(星期一) 中午11:53
收件人: "seanny1986/gym-aero"<gym-aero@noreply.github.com>;
抄送: "杨志鹏"<370479744@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [seanny1986/gym-aero] initial-value error (#11)




I pushed the latest version through -- took a while since I wanted to verify that the new simulation was working as intended. If you try inputting a hover command now, it should stay static.

**Comment by qwe3244968** [comment]
I am sorry that I may trouble you again.I downloaded “quadrotor-master” in your GITHUB and wanted to run the process named “landing_vedio”.But an error message has appeared that 'It is not currently possible to manually set the aspect ' .Have you ever meet this situation? I orry that I may trouble you again.I downloaded “quadrotor-master” in your GITHUB and wanted to run the process named “landing_vedio”.But an error message has appeared that 'It is not currently possible to manually set the aspect ' .Have you ever meet this situation? I look forward for your reply and thank you for your answer sincerely.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Sean Morrison"<notifications@github.com&gt;;
发送时间:&nbsp;2019年7月15日(星期一) 中午11:53
收件人:&nbsp;"seanny1986/gym-aero"<gym-aero@noreply.github.com&gt;;
抄送:&nbsp;"杨志鹏"<370479744@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [seanny1986/gym-aero] initial-value error (#11)




Closed #11.
